### ISSUE TITLE
SVN differences

### ISSUE THREAD

**Issue by infowolfe** [sackmotion/motion#1]
Why keep 2 codebases when they don't match each other? Confusion is the only result.

**Comment by tetherit** [comment]
Not quite sure about this either. I do like the code being in github, but what is the difference to the svn code? - any reason to use one over the other? - what is the plan for this repository?

**Comment by sackmotion** [comment]
Infowolfe , 

 you're right that has not sense to have on that way, i was not aware of that. I'll try to keep synced. 

Thanks !
