### ISSUE TITLE
Working version of ffmpeg?

### ISSUE THREAD

**Issue by cbs228** [sackmotion/motion#22]
I have tried to compile motion master-0-gad7e243 against several different versions of ffmpeg.
- The avconv packages in Ubuntu 13.10 (libavformat-dev 6:0.8.10-0ubuntu0.13.10.1). Motion compiles, but the resulting video has a framerate which is much lower than the video headers say it does.
- The official release of ffmpeg-0.11.5. Motion will not compile against this version and fails with: 
  `/home/me/bin/motion_src/netcam_rtsp.c:189: undefined reference to `av_err2str'`

I am not sure if the ffmpeg information on the wiki is up-to-date.

Can you provide the correct version of ffmpeg, via a git submodule, which is known to work?

**Comment by tosiara** [comment]
1. The incorrect framerate issue happens when your computer is not able to process frames at given fps. This results in "fast" videos. Try to reduce fps or check why your computer is so slow
2. I compile git trunk motion against current trunk ffmpeg without any errors. Use ./configure --with-ffmpeg=/path/to/compiled/installed/ffmpeg

**Comment by cbs228** [comment]
FFmpeg from git (master-0-g181b2c3) compiles okay. Since I don't want to replace my system libraries, I have installed it in my /home directory. My configure lines are

FFmpeg:

```
./configure --enable-gpl --enable-libx264 --enable-shared --enable-rpath --prefix=/home/me/motion
```

Motion:

```
./configure --with-ffmpeg=/home/me/motion --with-ffmpeg-headers=/home/me/motion --prefix=/home/me/motion    
```

With this build, however, it is necessary to invoke motion as

```
 $ LD_LIBRARY_PATH=/home/me/motion/lib bin/motion ...
```

as motion's ./configure script does not appear to have an `-rpath` option.

I want full HD video, so I am using 1280x720 at 24 fps with MJPEG. `guvcview` operates just fine in this mode, as does the motion SDL application. CPU usage weighs in at a comfortable 25% on my core i5. Running with the setup mode indicates that the motion detection portion works just fine. 

The videos output by ffmpeg with `ffmpeg_output_movies` are still glitchy, however. motion reports the output rate as 15 fps. This is far less than the 24 fps I had hoped to achieve, but it is consistent with the value encoded in the video files. There are far fewer frames in the file than that, however. The videos appear to be severely undersampled. If I dial the framerate down to 2 fps, the videos have several seconds of black screen, followed by a single still frame.

I also have motion 3.2.12 installed via my system's package manager ("motion" version 3.2.12-3.4 from Ubuntu universe). It appears to work just fine with this configuration, including the video output. I was hoping to use `extpipe` and a slightly more modern video codec than mpeg4, however, which aren't in the packaged version.

Perhaps I could set up motion to listen to an rtsp feed and use shell jobs to control recording. I don't need to do motion _detection_ at 24 fps; I just want to save movies at that frame rate.

**Comment by tosiara** [comment]
Can you please point me, what is the tree "master-0-gad7e243" of your motion?

**Comment by cbs228** [comment]
My HEAD is ad7e243fcaee500f67297305d9235556fb4270b9, "Fix configure libavformat / libavcodec"

**Comment by tosiara** [comment]
This tree does motion detection maximum at 3fps. I never used motion at rate higher than 15fps, so cant comment why you get laggy videos.
Also beware rtsp - it's in very deep beta/testing
And I would recommend you using exp_pipe. I use "x264" with "ultrafast" preset and I'm pretty happy with it running 720p@10fps on low power ARM device (mk808)

**Comment by cbs228** [comment]
I have lowered `framerate = 10`, disabled the internal ffmpeg video, and switched to using extpipe. My extpipe call is:

```
extpipe /home/me/motion/bin/ffmpeg -y -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -framerate %fps -i pipe:0 -c:v libx264 -pix_fmt yuv420p -preset ultrafast -crf 22 -f mp4 %f.mp4
```

The resulting video looks reasonable, but its framerate is still wrong. A 60 second capture (with emulate_motion turned on) yields a video which is only 20 seconds long, and the clock that is "burned" into the video runs fast. CPU usage looked okay during the test, although there could be some other bottleneck like RAM.

@tosiara, can you share your extpipe call? Perhaps I'm doing something wrong.

**Comment by tosiara** [comment]
I use this one:

```
extpipe x264 - --input-res 1280x720 --fps %fps --bitrate 1500 --preset ultrafast --quiet -o %f.mp4
```

**Comment by cbs228** [comment]
Even when using that exact `extpipe x264 ...` line, the actual framerate of the video is less than half of what it should be. x264 claims to be encoding frames at a rate of 2 or 3 fps, but the video claims to have 10 fps.

**Comment by tosiara** [comment]
Motion does not record all the frames. If there are no changed pixels -
motion does not send any frames to x264, that's why it reports lower frame
rate during encoding.

If you still reg resulting video with fps 10 instead of 24 - check why
motion drops frames. Try running with higher debug level and watch what
happens. Are you sure your hardware is ok?

**Comment by cbs228** [comment]
I did not realize that motion only outputs changed frames. By "changed," you mean frames where the threshold is met, correct? I have `emulate_motion` turned on in my test configuration. Will this bypass the changed-frame check and output every frame?

Here are some motion logs at debug level 8 and emulate_motion turned on: http://pastebin.com/2vPJBESW . As far as I can discern, the logs don't indicate any critical issues. This camera setup works just fine for full-HD video conferencing and runs in guvcview just fine at motion's resolution, color space, and frame rate.

I was really looking for full-framerate, full-HD recording of events. Perhaps I would have better luck trying to make motion control another program's recording capability.

**Comment by tosiara** [comment]
I'd suggest you to summarize your info, upload full config, log and video sample - and post to mail group - http://www.lavrsen.dk/foswiki/bin/view/Motion/MailingList

**Comment by cbs228** [comment]
Alright, I'm going to close this ticket until an actual motion bug is found.
